### ISSUE TITLE
Profile edit form validation errors are not displayed. 

### ISSUE THREAD

**Issue by ojedatony1616** [DistrictDataLabs/minimum-entropy#17]
It currently doesn't save the changes you made or close the Edit Profile view.

**Comment by bbengfort** [comment]
@ojedatony1616 can you be a bit more specific? It's working for me, and I don't see any errors in the logs?

**Comment by ojedatony1616** [comment]
@bbengfort I think it has to do with the bio part. Is there a character limit for that field? It let me update everything but that. When I copy and paste my bio from the DDL website into the short bio field, the Save Changes button doesn't work.

**Comment by bbengfort** [comment]
Ah - there is indeed a character limit (255 chars), so there are two problems here:
1. Invalid uploads should be displayed on the form if there is trouble. 
2. The biography should be updated to be a bit longer. 

This is definitely research code; the Logbook and Trinket apps have more robust profile tools that can be brought over.

**Comment by bbengfort** [comment]
I believe this is fixed now.
